theme: jekyll-theme-minimal
title: Welcome to my homepage!
description: Hi, my name is Johannes Thalhammer, I am a doctoral candidate at the Chair of Biomedical Imaging, Technical University Munich. 
